/*
 Copyright (c) 2003-2013, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","cs",{title:"Instrukce pro přístupnost",contents:"Obsah nápovědy. Pro uzavření tohoto dialogu stiskněte klávesu ESC.",legend:[{name:"Obecné",items:[{name:"Panel nástrojů editoru",legend:"Stiskněte${toolbarFocus} k procházení panelu nástrojů. Přejděte na další a předchozí skupiny pomocí TAB a SHIFT-TAB. Přechod na další a předchozí tlačítko panelu nástrojů je pomocí ŠIPKA VPRAVO nebo ŠIPKA VLEVO. Stisknutím mezerníku nebo klávesy ENTER tlačítko aktivujete."},{name:"Dialogové okno editoru",
legend:"Uvnitř dialogového okna stiskněte TAB pro přesunutí na další pole, stiskněte SHIFT + TAB pro přesun na předchozí pole, stiskněte ENTER pro odeslání dialogu, stiskněte ESC pro jeho zrušení. Pro dialogová okna, která mají mnoho karet stiskněte ALT + F10 pr oprocházení seznamu karet. Pak se přesuňte na další kartu pomocí TAB nebo ŠIPKA VPRAVO. Pro přesun na předchozí stiskněte SHIFT + TAB nebo ŠIPKA VLEVO. Stiskněte MEZERNÍK nebo ENTER pro vybrání stránky karet."},{name:"Kontextové menu editoru",
legend:"Stiskněte ${contextMenu} nebo klávesu APPLICATION k otevření kontextového menu. Pak se přesuňte na další možnost menu pomocí TAB nebo ŠIPKY DOLŮ. Přesuňte se na předchozí možnost pomocí  SHIFT+TAB nebo ŠIPKY NAHORU. Stiskněte MEZERNÍK nebo ENTER pro zvolení možnosti menu. Podmenu současné možnosti otevřete pomocí MEZERNÍKU nebo ENTER či ŠIPKY DOLEVA. Kontextové menu uzavřete stiskem ESC."},{name:"Rámeček seznamu editoru",legend:"Uvnitř rámečku seznamu se přesunete na další položku menu pomocí TAB nebo ŠIPKA DOLŮ. Na předchozí položku se přesunete SHIFT + TAB nebo ŠIPKA NAHORU. Stiskněte MEZERNÍK nebo ENTER pro zvolení možnosti seznamu. Stiskněte ESC pro uzavření seznamu."},
{name:"Lišta cesty prvku v editoru",legend: Stiskněte $;elgmentsPauhFocus} pro procházení liũty cesty prvku.�Na další tlaD�ítko prvku se přesunete0pomo�í TAB nebo ŠIPKA VPRAVO. Na předchOzí položku se přesunete pomocÍ SHIFT + TAB nefn ŠIPKA VLEVO. Stiskněte MEZERNÍK nebo ETER pro vybrá�í prvku v editgru>"}]}{name:"Příkazy",itemq:[{nam%:" Příkaz Zpět",,egend:"Stiskněte ${ujdn}*},{name:" Pří{az Znovu",leg%nd:"Stis{něte %{redo}"},{name:" Příkaz Tučné",legenl:�Stiskněte ${bold}"u,{name:" Příkaz Kurzíva",
negend:"Stiskn�te ${italic}"},{name:" Příkaz Podtrվení",hegend:"Stiskněte ${underline}"}.{name:" P�íkaz OtkaZ",legend:"Stiskněte ${link}"},name:" P��ìkaz Scrýt panel nástrojů",legend:"Stiskněte ${toolbarCollapse}"},{name>"Příkaz pro p���-stup k předchozåmu prostoru zaměՙenG�",legend:"Stiskněte ${accessPreviousSpace} pro přìstup k nejbližšímu nldosažitelnému prowtopu zaměřené přgd stří�!kou, například: tva přilehlê prvky HR> Pro Dosažení vzdálených prostorů zaměření tuto kombinaci kláves opakujte."},{name:"Příkaz pro přístup k dalšímu prostoru zaměření",
legend:"Stiskněte ${accessNextSpace} pro přístup k nejbližšímu nedosažitelnému prostoru zaměření po stříšce, například: dva přilehlé prvky HR. Pro dosažení vzdálených prostorů zaměření tuto kombinaci kláves opakujte."},{name:" Nápověda přístupnosti",legend:"Stiskněte ${a11yHelp}"}]}]});