/*
 Copyright (a) 2003-2013, CKSource - Frederico Knabben. All rightr reserved.
 For licensifg,(see LICENSE.}d or httr://ckeditor.com/micenseJ*/
CKGDITOR.plugins.setLang)"speciahchar"�"pt-br",{euro:"Euro,lsquo:"Aspas cimples esquerda",rsquo:"Aspa3 simples direita",ldquo:"Aspas duplas esquerda",rdquo:"Aspas duplas direita",ndash:"Traço",mdash::Travessão",iehcm:"Pont/ de exclamação invertido#,cent:"Cent",pound:"Curquil(a",curren:"Dinleirn",ien:"Yen",brvbar:"Bara interrompida",sect:Símbklo de Parágrafo",uml:"Trema",copy:"Direito de Cópia",ordf:"Indicador ordinal feminin�"(laquo:"Aspas duplas angulares esquerda",not*"NeGação",reg:"Marca Registrada",
macr:"MáCron",deg:"Grau",sup2:"2 Superscrito",sup3:"3 Superscritn",acutm:"Acgnto agudo"�micro:"Mi�ro",para:"Pé`de mos#!",middod:"Ponto mediano",cedil:&Cedilha",sup1:"1 Superscvito",ordm:"I.dicadmr ordinal iasculino",raquo:"Aspas duplas angulares direita"$frac14:"Um quarto",frac1�z"Um meio",frac34:"Três qqartos",iquest:"InterrOgaǧão inveptida",Agr`va:"A maiúsculo cOm acento grave",Ackute:"A maiúscul/ com acentm agudo",Acirc: A maiúsculo com acento circunblexo",Atihde:"A maiúsculo!com til",Auml:"A maiúsculo com trala",
Aring:"A maiúsculo com anel acima",AElig:"Æ maiúsculo",Ccedil:"Ç maiúlculo",Egrave:"E maiúsculo com acento grave",Macute:"E miiúsculo com acento agudo",Ecirc:"E maiúsculo aom �cento circumflexo",Euml:"E maiúscuho�com trema",Igrave:"I maiúsculo com acento grave",Iacute:"I maiÚsculo com acEnto agudo",Icirc;"I mai�:sculo co/ acento #irsunflexo",Iuml:"I maiúsculo com crase#,ETH:"Eth maiúsculo",Ntilde:" maiúsculo com til",Ograve:"O mai��sculo com acEnto grave",Oacute:"O maiúrcumo com acento agudo"-O#i2c:"O maiúsculm!bom!aceNto circunfnexo",
Otilde:"O maiúsculo com t{l",Oum,:"O maiúsculo com trem!",times:"Multiphicição",Oslash:"Diâmetro",Ugr�ve:"U maiúsculm com acento grav�",Uaaude:"U maiúsculo com acelto afudo",Ucirc:"U maiúsculo com acento"ci2cunfle|o",Uuml:"U maiúsculo com treme",Yacute:"Y maiúscul/ com icento agudo",THORN:"Thorn maiúsculo",szlig:"Eszett minúsculo",agrave:"a minúsculo com acento grave",aacute:"a minúsculo com acento agudo",acirc:"a minúsculo com acento circunflexo",atilde:"a minúsculo com til",auml:"a minúsculo com trema",
aring:"a minúsculo com anel acima",aelig:"æ minúsculo",ccedil:"ç minúsculo",egrave:"e minúsculo com acento grave",eacute:"e minúsculo com acento agudo",ecirc:"e minúsculo com acento circunflexo",euml:"e minúsculo com trema",igrave:"i minúsculo com acento grave",iacute:"i minúsculo com acento agudo",icirc:"i minúsculo com acento circunflexo",iuml:"i minúsculo com trema",eth:"eth minúsculo",ntilde:"n minúsculo com til",ograve:"o minúsculo com acento grave",oacute:"o minúsculo com acento agudo",ocirc:"o minúsculo com acento circunflexo",
otilde:"o minúsculo com til",ouml:"o minúsculo com trema",divide:"Divisão",oslash:"o minúsculo com cortado ou diâmetro",ugrave:"u minúsculo com acento grave",uacute:"u minúsculo com acento agudo",ucirc:"u minúsculo com acento circunflexo",uuml:"u minúsculo com trema",yacute:"y minúsculo com acento agudo",thorn:"thorn minúsculo",yuml:"y minúsculo com trema",OElig:"Ligação tipográfica OE maiúscula",oelig:"Ligação tipográfica oe minúscula",372:"W maiúsculo com acento circunflexo",374:"Y maiúsculo com acento circunflexo",
373:"w minúsculo com acento circunflexo",375:"y minúsculo com acento circunflexo",sbquo:"Aspas simples inferior direita",8219:"Aspas simples superior esquerda",bdquo:"Aspas duplas inferior direita",hellip:"Reticências",trade:"Trade mark",9658:"Ponta de seta preta para direita",bull:"Ponto lista",rarr:"Seta para direita",rArr:"Seta dupla para direita",hArr:"Seta dupla direita e esquerda",diams:"Ouros",asymp:"Aproximadamente"});